defaults:
  - train_larc
  - _self_

output_dir: ${oc.env:ACT_LEWM_RUN_ROOT}/pusht/horizon_h50/larc

world_model:
  config_path: ${oc.env:ACT_LEWM_RUN_ROOT}/pusht/horizon_h50/world_model/model_config.yaml
  weights_path: ${oc.env:ACT_LEWM_RUN_ROOT}/pusht/horizon_h50/world_model/fast_lewm_backbone_best.pt

data:
  frameskip: 5
  max_horizon: 10

wandb:
  config:
    name: larc-h50-pusht
